name: Publish to NPM
on:
  push:
    branches:
      - master
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
      
      - name: Build
        run: |
          npm run build
          npm run pack

      - name: Publish
        uses: pascalgn/npm-publish-action@1.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
