name: Test and Report Coverage
on: push
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
      
      - name: Generate Coverage Report
        run: npm run cov:gen

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1

